server:
  port: 8080

spring:
   application:
     name: ead-api-gateway
   cloud:
     gateway:
       routes:
         - id: authuser
           uri: http://localhost:8087/
           predicates:
             - Path=/ead-authuser/**
